/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as SchoolAdminRouteRouteImport } from './routes/school-admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as SchoolAdminIndexRouteImport } from './routes/school-admin/index'
import { Route as SuperAdminVideoReleasesRouteImport } from './routes/super-admin/video-releases'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin/schools'
import { Route as SuperAdminQuizzesRouteImport } from './routes/super-admin/quizzes'
import { Route as SuperAdminCoursesRouteImport } from './routes/super-admin/courses'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentCertificatesRouteImport } from './routes/student/certificates'
import { Route as StudentAiTutorRouteImport } from './routes/student/ai-tutor'
import { Route as StudentAiNotesRouteImport } from './routes/student/ai-notes'
import { Route as StudentAiInsightsRouteImport } from './routes/student/ai-insights'
import { Route as SchoolAdminStudentsRouteImport } from './routes/school-admin/students'
import { Route as SchoolAdminReportsRouteImport } from './routes/school-admin/reports'
import { Route as SchoolAdminAnalyticsRouteImport } from './routes/school-admin/analytics'
import { Route as AuthStudentLoginRouteImport } from './routes/auth/student-login'
import { Route as AuthSchoolAdminLoginRouteImport } from './routes/auth/school-admin-login'
import { Route as StudentQuizQuizIdRouteImport } from './routes/student/quiz.$quizId'
import { Route as StudentLearnCourseIdRouteImport } from './routes/student/learn.$courseId'
import { Route as StudentCourseCourseIdRouteImport } from './routes/student/course.$courseId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAdminRouteRoute = SchoolAdminRouteRouteImport.update({
  id: '/school-admin',
  path: '/school-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const SchoolAdminIndexRoute = SchoolAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolAdminRouteRoute,
} as any)
const SuperAdminVideoReleasesRoute = SuperAdminVideoReleasesRouteImport.update({
  id: '/video-releases',
  path: '/video-releases',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminQuizzesRoute = SuperAdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminCoursesRoute = SuperAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAiTutorRoute = StudentAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAiNotesRoute = StudentAiNotesRouteImport.update({
  id: '/ai-notes',
  path: '/ai-notes',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAiInsightsRoute = StudentAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => StudentRouteRoute,
} as any)
const SchoolAdminStudentsRoute = SchoolAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SchoolAdminRouteRoute,
} as any)
const SchoolAdminReportsRoute = SchoolAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SchoolAdminRouteRoute,
} as any)
const SchoolAdminAnalyticsRoute = SchoolAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SchoolAdminRouteRoute,
} as any)
const AuthStudentLoginRoute = AuthStudentLoginRouteImport.update({
  id: '/auth/student-login',
  path: '/auth/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSchoolAdminLoginRoute = AuthSchoolAdminLoginRouteImport.update({
  id: '/auth/school-admin-login',
  path: '/auth/school-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizQuizIdRoute = StudentQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentLearnCourseIdRoute = StudentLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCourseCourseIdRoute = StudentCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => StudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/school-admin': typeof SchoolAdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/auth/school-admin-login': typeof AuthSchoolAdminLoginRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/students': typeof SchoolAdminStudentsRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/ai-notes': typeof StudentAiNotesRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/quizzes': typeof SuperAdminQuizzesRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/video-releases': typeof SuperAdminVideoReleasesRoute
  '/school-admin/': typeof SchoolAdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/auth/school-admin-login': typeof AuthSchoolAdminLoginRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/students': typeof SchoolAdminStudentsRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/ai-notes': typeof StudentAiNotesRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/quizzes': typeof SuperAdminQuizzesRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/video-releases': typeof SuperAdminVideoReleasesRoute
  '/school-admin': typeof SchoolAdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/school-admin': typeof SchoolAdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/auth/school-admin-login': typeof AuthSchoolAdminLoginRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/students': typeof SchoolAdminStudentsRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/ai-notes': typeof StudentAiNotesRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/quizzes': typeof SuperAdminQuizzesRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/video-releases': typeof SuperAdminVideoReleasesRoute
  '/school-admin/': typeof SchoolAdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/school-admin'
    | '/student'
    | '/super-admin'
    | '/about'
    | '/courses'
    | '/instructors'
    | '/pricing'
    | '/auth/school-admin-login'
    | '/auth/student-login'
    | '/school-admin/analytics'
    | '/school-admin/reports'
    | '/school-admin/students'
    | '/student/ai-insights'
    | '/student/ai-notes'
    | '/student/ai-tutor'
    | '/student/certificates'
    | '/student/courses'
    | '/super-admin/courses'
    | '/super-admin/quizzes'
    | '/super-admin/schools'
    | '/super-admin/video-releases'
    | '/school-admin/'
    | '/student/'
    | '/super-admin/'
    | '/student/course/$courseId'
    | '/student/learn/$courseId'
    | '/student/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/instructors'
    | '/pricing'
    | '/auth/school-admin-login'
    | '/auth/student-login'
    | '/school-admin/analytics'
    | '/school-admin/reports'
    | '/school-admin/students'
    | '/student/ai-insights'
    | '/student/ai-notes'
    | '/student/ai-tutor'
    | '/student/certificates'
    | '/student/courses'
    | '/super-admin/courses'
    | '/super-admin/quizzes'
    | '/super-admin/schools'
    | '/super-admin/video-releases'
    | '/school-admin'
    | '/student'
    | '/super-admin'
    | '/student/course/$courseId'
    | '/student/learn/$courseId'
    | '/student/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/school-admin'
    | '/student'
    | '/super-admin'
    | '/about'
    | '/courses'
    | '/instructors'
    | '/pricing'
    | '/auth/school-admin-login'
    | '/auth/student-login'
    | '/school-admin/analytics'
    | '/school-admin/reports'
    | '/school-admin/students'
    | '/student/ai-insights'
    | '/student/ai-notes'
    | '/student/ai-tutor'
    | '/student/certificates'
    | '/student/courses'
    | '/super-admin/courses'
    | '/super-admin/quizzes'
    | '/super-admin/schools'
    | '/super-admin/video-releases'
    | '/school-admin/'
    | '/student/'
    | '/super-admin/'
    | '/student/course/$courseId'
    | '/student/learn/$courseId'
    | '/student/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchoolAdminRouteRoute: typeof SchoolAdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRoute
  InstructorsRoute: typeof InstructorsRoute
  PricingRoute: typeof PricingRoute
  AuthSchoolAdminLoginRoute: typeof AuthSchoolAdminLoginRoute
  AuthStudentLoginRoute: typeof AuthStudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-admin': {
      id: '/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof SchoolAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/school-admin/': {
      id: '/school-admin/'
      path: '/'
      fullPath: '/school-admin/'
      preLoaderRoute: typeof SchoolAdminIndexRouteImport
      parentRoute: typeof SchoolAdminRouteRoute
    }
    '/super-admin/video-releases': {
      id: '/super-admin/video-releases'
      path: '/video-releases'
      fullPath: '/super-admin/video-releases'
      preLoaderRoute: typeof SuperAdminVideoReleasesRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/quizzes': {
      id: '/super-admin/quizzes'
      path: '/quizzes'
      fullPath: '/super-admin/quizzes'
      preLoaderRoute: typeof SuperAdminQuizzesRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/courses': {
      id: '/super-admin/courses'
      path: '/courses'
      fullPath: '/super-admin/courses'
      preLoaderRoute: typeof SuperAdminCoursesRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ai-tutor': {
      id: '/student/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof StudentAiTutorRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ai-notes': {
      id: '/student/ai-notes'
      path: '/ai-notes'
      fullPath: '/student/ai-notes'
      preLoaderRoute: typeof StudentAiNotesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ai-insights': {
      id: '/student/ai-insights'
      path: '/ai-insights'
      fullPath: '/student/ai-insights'
      preLoaderRoute: typeof StudentAiInsightsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/school-admin/students': {
      id: '/school-admin/students'
      path: '/students'
      fullPath: '/school-admin/students'
      preLoaderRoute: typeof SchoolAdminStudentsRouteImport
      parentRoute: typeof SchoolAdminRouteRoute
    }
    '/school-admin/reports': {
      id: '/school-admin/reports'
      path: '/reports'
      fullPath: '/school-admin/reports'
      preLoaderRoute: typeof SchoolAdminReportsRouteImport
      parentRoute: typeof SchoolAdminRouteRoute
    }
    '/school-admin/analytics': {
      id: '/school-admin/analytics'
      path: '/analytics'
      fullPath: '/school-admin/analytics'
      preLoaderRoute: typeof SchoolAdminAnalyticsRouteImport
      parentRoute: typeof SchoolAdminRouteRoute
    }
    '/auth/student-login': {
      id: '/auth/student-login'
      path: '/auth/student-login'
      fullPath: '/auth/student-login'
      preLoaderRoute: typeof AuthStudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/school-admin-login': {
      id: '/auth/school-admin-login'
      path: '/auth/school-admin-login'
      fullPath: '/auth/school-admin-login'
      preLoaderRoute: typeof AuthSchoolAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quiz/$quizId': {
      id: '/student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/student/quiz/$quizId'
      preLoaderRoute: typeof StudentQuizQuizIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/learn/$courseId': {
      id: '/student/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/student/learn/$courseId'
      preLoaderRoute: typeof StudentLearnCourseIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/course/$courseId': {
      id: '/student/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/student/course/$courseId'
      preLoaderRoute: typeof StudentCourseCourseIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface SchoolAdminRouteRouteChildren {
  SchoolAdminAnalyticsRoute: typeof SchoolAdminAnalyticsRoute
  SchoolAdminReportsRoute: typeof SchoolAdminReportsRoute
  SchoolAdminStudentsRoute: typeof SchoolAdminStudentsRoute
  SchoolAdminIndexRoute: typeof SchoolAdminIndexRoute
}

const SchoolAdminRouteRouteChildren: SchoolAdminRouteRouteChildren = {
  SchoolAdminAnalyticsRoute: SchoolAdminAnalyticsRoute,
  SchoolAdminReportsRoute: SchoolAdminReportsRoute,
  SchoolAdminStudentsRoute: SchoolAdminStudentsRoute,
  SchoolAdminIndexRoute: SchoolAdminIndexRoute,
}

const SchoolAdminRouteRouteWithChildren =
  SchoolAdminRouteRoute._addFileChildren(SchoolAdminRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentAiInsightsRoute: typeof StudentAiInsightsRoute
  StudentAiNotesRoute: typeof StudentAiNotesRoute
  StudentAiTutorRoute: typeof StudentAiTutorRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCourseCourseIdRoute: typeof StudentCourseCourseIdRoute
  StudentLearnCourseIdRoute: typeof StudentLearnCourseIdRoute
  StudentQuizQuizIdRoute: typeof StudentQuizQuizIdRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAiInsightsRoute: StudentAiInsightsRoute,
  StudentAiNotesRoute: StudentAiNotesRoute,
  StudentAiTutorRoute: StudentAiTutorRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCourseCourseIdRoute: StudentCourseCourseIdRoute,
  StudentLearnCourseIdRoute: StudentLearnCourseIdRoute,
  StudentQuizQuizIdRoute: StudentQuizQuizIdRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface SuperAdminRouteRouteChildren {
  SuperAdminCoursesRoute: typeof SuperAdminCoursesRoute
  SuperAdminQuizzesRoute: typeof SuperAdminQuizzesRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRoute
  SuperAdminVideoReleasesRoute: typeof SuperAdminVideoReleasesRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminCoursesRoute: SuperAdminCoursesRoute,
  SuperAdminQuizzesRoute: SuperAdminQuizzesRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRoute,
  SuperAdminVideoReleasesRoute: SuperAdminVideoReleasesRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchoolAdminRouteRoute: SchoolAdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRoute,
  InstructorsRoute: InstructorsRoute,
  PricingRoute: PricingRoute,
  AuthSchoolAdminLoginRoute: AuthSchoolAdminLoginRoute,
  AuthStudentLoginRoute: AuthStudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
